version: "3.9"

services:
  apps:
    container_name: boilerplate_serverless
    image: node:18.16
    command: /bin/sh -c "npm install && npm run watch"
    environment:
      NODE_ENV: development
      APP_ENV: development
    working_dir: /var/app/current
    volumes:
      - "./apps:/var/app/current"
    networks:
      - boilerplate_serverless_network

networks:
  boilerplate_serverless_network:
    driver: bridge

volumes:
  local_mysql_data: