AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: App template for boilerplate serverless

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    CodeUri: ../../../apps
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 60

Resources:
  ListRolesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ListRoles
      Description: Function to list roles
      Handler: build/handlers/roles/list.handler
      Events:
        App:
          Type: Api
          Properties:
            Path: /roles
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/roles/list.ts

  ReadRolesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ReadRoles
      Description: Function to read roles
      Handler: build/handlers/roles/read.handler
      Events:
        App:
          Type: Api
          Properties:
            Path: /roles/{id}
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/roles/read.ts

  CreateRolesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateRoles
      Description: Function to create roles
      Handler: build/handlers/roles/create.handler
      Events:
        App:
          Type: Api
          Properties:
            Path: /roles
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/roles/create.ts

  UpdateRolesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UpdateRoles
      Description: Function to update roles
      Handler: build/handlers/roles/update.handler
      Events:
        App:
          Type: Api
          Properties:
            Path: /roles/{id}
            Method: put
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/roles/update.ts

  DeleteRolesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DeleteRoles
      Description: Function to delete roles
      Handler: build/handlers/roles/delete.handler
      Events:
        App:
          Type: Api
          Properties:
            Path: /roles/{id}
            Method: delete
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/roles/delete.ts

  DeleteByIdsRolesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DeleteByIdsRoles
      Description: Function to delete roles by ids
      Handler: build/handlers/roles/delete-by-ids.handler
      Events:
        App:
          Type: Api
          Properties:
            Path: /roles/delete-by-ids
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/roles/delete-by-ids.ts