AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Main template for boilerplate serverless

Resources:
  AppApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./apps/app-template.yaml